/*
 * Auto-generated by Block Robot IDE
 * Target: ESP32 (Arm Controller)
 */

#define BLYNK_TEMPLATE_ID "{{BLYNK_TEMPLATE_ID}}"
#define BLYNK_TEMPLATE_NAME "{{BLYNK_TEMPLATE_NAME}}"
#define BLYNK_AUTH_TOKEN "{{BLYNK_AUTH_TOKEN}}"

#include <WiFi.h>
#include <BlynkSimpleEsp32.h>
#include <ESP32Servo.h>

// WiFi credentials
char ssid[] = "{{WIFI_SSID}}";
char pass[] = "{{WIFI_PASSWORD}}";

// Servo objects
Servo servoBase, servoShoulder, servoElbow, servoWrist, servoGripper;

// GPIO pins (PLACEHOLDER - update during hardware testing)
const int PIN_BASE = 12;
const int PIN_SHOULDER = 13;
const int PIN_ELBOW = 14;
const int PIN_WRIST = 15;
const int PIN_GRIPPER = 16;

// Gripper positions
const int GRIPPER_OPEN = 30;
const int GRIPPER_CLOSE = 90;

// Operating mode
bool autoMode = false;

// Vision data from ESP32-CAM (via Blynk)
String lastDetection = "none";
int lastConfidence = 0;

// Pose definitions (generated from IDE)
{{POSE_DEFINITIONS}}

void setup() {
  Serial.begin(115200);

  // Attach servos
  servoBase.attach(PIN_BASE);
  servoShoulder.attach(PIN_SHOULDER);
  servoElbow.attach(PIN_ELBOW);
  servoWrist.attach(PIN_WRIST);
  servoGripper.attach(PIN_GRIPPER);

  // Connect to Blynk
  Blynk.begin(BLYNK_AUTH_TOKEN, ssid, pass);
  Serial.println("Arm controller ready");
}

void loop() {
  Blynk.run();

  if (autoMode) {
    runStudentProgram();
    delay(100);
  }
}

// Helper functions exposed to generated code

void moveArmToPose(const int pose[5]) {
  servoBase.write(pose[0]);
  servoShoulder.write(pose[1]);
  servoElbow.write(pose[2]);
  servoWrist.write(pose[3]);
  servoGripper.write(pose[4]);
  delay(500); // Allow servos to reach position
}

void openClaw() {
  servoGripper.write(GRIPPER_OPEN);
  delay(300);
}

void closeClaw() {
  servoGripper.write(GRIPPER_CLOSE);
  delay(300);
}

bool cameraSees(const String& className, int minConfidence) {
  return (lastDetection == className && lastConfidence >= minConfidence);
}

// Blynk virtual pin handlers

BLYNK_WRITE(V0) {  // Base angle (manual mode only)
  if (!autoMode) servoBase.write(param.asInt());
}

BLYNK_WRITE(V1) {  // Shoulder angle (manual mode only)
  if (!autoMode) servoShoulder.write(param.asInt());
}

BLYNK_WRITE(V2) {  // Elbow angle (manual mode only)
  if (!autoMode) servoElbow.write(param.asInt());
}

BLYNK_WRITE(V3) {  // Wrist angle (manual mode only)
  if (!autoMode) servoWrist.write(param.asInt());
}

BLYNK_WRITE(V4) {  // Gripper angle (manual mode only)
  if (!autoMode) servoGripper.write(param.asInt());
}

BLYNK_WRITE(V5) {  // Auto/Manual mode toggle
  autoMode = (param.asInt() == 1);
  Serial.println(autoMode ? "Auto mode ON" : "Manual mode ON");
}

BLYNK_WRITE(V10) {  // Detection class from ESP32-CAM
  lastDetection = param.asString();
}

BLYNK_WRITE(V11) {  // Detection confidence from ESP32-CAM
  lastConfidence = param.asInt();
}

// Student-generated code goes here
void runStudentProgram() {
  {{GENERATED_CODE}}
}
