/*
 * Auto-generated by Block Robot IDE
 * Target: ESP32 + PCA9685 servo driver (standalone, no cloud dependency)
 *
 * This template drives five servos through a PCA9685 I2C PWM driver.
 * Control is via the WebSocket interface (see arm_controller_ap_mode.ino
 * for the full AP-mode + embedded web UI version used in production).
 */

#include <Wire.h>
#include <Adafruit_PWMServoDriver.h>

// I2C pins for ESP32
#define SDA_PIN 21
#define SCL_PIN 22

// Logical servo indices
#define SERVO_BASE     0
#define SERVO_SHOULDER 1
#define SERVO_ELBOW    2
#define SERVO_WRIST    3
#define SERVO_GRIPPER  4

// Physical PCA9685 output channel each servo is wired to.
// Change to match your wiring without touching anything else.
const uint8_t PWM_CHANNEL[5] = {0, 2, 4, 6, 8};

// PWM frequency for servos (50 Hz standard)
#define SERVO_FREQ 50

// Per-servo pulse calibration (adjust if a servo doesn't reach full range).
// PULSE_MIN = pulse at 0°, PULSE_MAX = pulse at max angle.
const int SERVO_PULSE_MIN[5] = {150, 150, 150, 150, 150};
const int SERVO_PULSE_MAX[5] = {450, 450, 450, 450, 450};

// Per-channel travel range.
const int SERVO_MAX_ANGLE[5] = {180, 180, 180, 90, 90};

// Channels whose direction is physically reversed.
const bool SERVO_INVERTED[5] = {false, true, false, true, false};

// Gripper open/close angles.
const int GRIPPER_OPEN  = 30;
const int GRIPPER_CLOSE = 15;

// Default ("home") positions.
const int DEFAULT_POSITIONS[5] = {90, 90, 90, 60, 0};

// PCA9685 driver instance (default I2C address 0x40)
Adafruit_PWMServoDriver pwm = Adafruit_PWMServoDriver();

// Current servo positions
int currentPos[5] = {90, 90, 90, 60, 0};

// Pose definitions (generated from IDE)
{{POSE_DEFINITIONS}}

// Convert a logical angle on servo s to a PWM pulse count.
int angleToPulse(uint8_t servo, int angle) {
  if (servo >= 5) return map(constrain(angle, 0, 180), 0, 180, 100, 500);
  int maxAngle = SERVO_MAX_ANGLE[servo];
  angle = constrain(angle, 0, maxAngle);
  if (SERVO_INVERTED[servo]) angle = maxAngle - angle;
  return map(angle, 0, maxAngle, SERVO_PULSE_MIN[servo], SERVO_PULSE_MAX[servo]);
}

// Drive a servo immediately to a logical angle.
void writeServo(uint8_t servo, int angle) {
  if (servo >= 5) return;
  pwm.setPWM(PWM_CHANNEL[servo], 0, angleToPulse(servo, angle));
  currentPos[servo] = angle;
}

void setup() {
  Serial.begin(115200);
  Serial.println("Starting arm controller (PCA9685)...");

  Wire.begin(SDA_PIN, SCL_PIN);
  pwm.begin();
  pwm.setPWMFreq(SERVO_FREQ);
  delay(10);

  for (int i = 0; i < 5; i++) {
    writeServo(i, DEFAULT_POSITIONS[i]);
  }
  Serial.println("PCA9685 initialized — servos at home position.");
}

void loop() {
  runStudentProgram();
  delay(100);
}

// ── helpers available to generated code ──────────────────────────────────────

void moveArmToPose(const int pose[5]) {
  for (int i = 0; i < 5; i++) writeServo(i, pose[i]);
  delay(500);
}

void openClaw() {
  writeServo(SERVO_GRIPPER, GRIPPER_OPEN);
  delay(300);
}

void closeClaw() {
  writeServo(SERVO_GRIPPER, GRIPPER_CLOSE);
  delay(300);
}

bool cameraSees(const String& className, int minConfidence) {
  // Detection runs on the PC, not on the ESP32.
  // The AP-mode firmware (arm_controller_ap_mode.ino) receives detection
  // results over WebSocket from the block runner. This standalone template
  // always returns false — use the AP-mode template for live detection.
  return false;
}

// Student-generated code
void runStudentProgram() {
  {{GENERATED_CODE}}
}
