/*
 * Auto-generated by Block Robot IDE
 * Target: ESP32 (Arm Controller with PCA9685 Servo Driver)
 */

#define BLYNK_TEMPLATE_ID "{{BLYNK_TEMPLATE_ID}}"
#define BLYNK_TEMPLATE_NAME "{{BLYNK_TEMPLATE_NAME}}"
#define BLYNK_AUTH_TOKEN "{{BLYNK_AUTH_TOKEN}}"

#include <WiFi.h>
#include <BlynkSimpleEsp32.h>
#include <Wire.h>
#include <Adafruit_PWMServoDriver.h>

// WiFi credentials
char ssid[] = "{{WIFI_SSID}}";
char pass[] = "{{WIFI_PASSWORD}}";

// PCA9685 servo driver (I2C address 0x40 by default)
Adafruit_PWMServoDriver pwm = Adafruit_PWMServoDriver();

// I2C pins for ESP32
#define SDA_PIN 21
#define SCL_PIN 22

// Servo channel assignments on PCA9685
#define SERVO_BASE     0  // Channel 0
#define SERVO_SHOULDER 1  // Channel 1
#define SERVO_ELBOW    2  // Channel 2
#define SERVO_WRIST    3  // Channel 3
#define SERVO_GRIPPER  4  // Channel 4

// PWM frequency for servos (50Hz standard)
#define SERVO_FREQ 50

// PWM pulse length range (adjust these if your servos behave differently)
// Most servos: 150 = 0°, 600 = 180°
// If servo doesn't reach full range, adjust SERVOMIN/SERVOMAX
#define SERVOMIN  150  // Minimum pulse length (0 degrees)
#define SERVOMAX  600  // Maximum pulse length (180 degrees)

// Gripper positions
const int GRIPPER_OPEN = 30;
const int GRIPPER_CLOSE = 90;

// Operating mode
bool autoMode = false;

// Vision data from ESP32-CAM (via Blynk)
String lastDetection = "none";
int lastConfidence = 0;

// Current servo positions (for smooth movement)
int currentPos[5] = {90, 90, 90, 90, 30}; // Base, Shoulder, Elbow, Wrist, Gripper

// Pose definitions (generated from IDE)
{{POSE_DEFINITIONS}}

// Helper function: Convert angle (0-180) to PWM pulse length
int angleToPulse(int angle) {
  // Constrain angle to valid range
  angle = constrain(angle, 0, 180);

  // Map angle to pulse length
  return map(angle, 0, 180, SERVOMIN, SERVOMAX);
}

// Helper function: Set servo position by channel
void setServoAngle(uint8_t channel, int angle) {
  int pulse = angleToPulse(angle);
  pwm.setPWM(channel, 0, pulse);

  // Update current position
  if (channel < 5) {
    currentPos[channel] = angle;
  }
}

void setup() {
  Serial.begin(115200);
  Serial.println("Starting Arm Controller with PCA9685...");

  // Initialize I2C
  Wire.begin(SDA_PIN, SCL_PIN);

  // Initialize PCA9685
  pwm.begin();
  pwm.setPWMFreq(SERVO_FREQ);

  // Wait for PCA9685 to stabilize
  delay(10);

  // Set all servos to initial positions
  setServoAngle(SERVO_BASE, 90);
  setServoAngle(SERVO_SHOULDER, 60);
  setServoAngle(SERVO_ELBOW, 70);
  setServoAngle(SERVO_WRIST, 60);
  setServoAngle(SERVO_GRIPPER, 90);

  Serial.println("PCA9685 initialized");

  // Connect to Blynk
  Serial.print("Connecting to WiFi: ");
  Serial.println(ssid);
  Blynk.begin(BLYNK_AUTH_TOKEN, ssid, pass);

  Serial.println("Arm controller ready");
}

void loop() {
  Blynk.run();

  if (autoMode) {
    runStudentProgram();
    delay(100);
  }
}

// Helper functions exposed to generated code

void moveArmToPose(const int pose[5]) {
  setServoAngle(SERVO_BASE, pose[0]);
  setServoAngle(SERVO_SHOULDER, pose[1]);
  setServoAngle(SERVO_ELBOW, pose[2]);
  setServoAngle(SERVO_WRIST, pose[3]);
  setServoAngle(SERVO_GRIPPER, pose[4]);
  delay(500); // Allow servos to reach position
}

void openClaw() {
  setServoAngle(SERVO_GRIPPER, GRIPPER_OPEN);
  delay(300);
}

void closeClaw() {
  setServoAngle(SERVO_GRIPPER, GRIPPER_CLOSE);
  delay(300);
}

bool cameraSees(const String& className, int minConfidence) {
  return (lastDetection == className && lastConfidence >= minConfidence);
}

// Blynk virtual pin handlers

BLYNK_CONNECTED() {
  // Sync slider values with actual servo positions on connect
  Blynk.virtualWrite(V0, 0);    // Base
  Blynk.virtualWrite(V1, 60);   // Shoulder
  Blynk.virtualWrite(V2, 70);   // Elbow
  Blynk.virtualWrite(V3, 60);   // Wrist
  Blynk.virtualWrite(V4, 90);   // Gripper
  Blynk.virtualWrite(V5, 0);
  Serial.println("Blynk connected - synced slider values");
}

BLYNK_WRITE(V0) {  // Base angle (manual mode only)
  if (!autoMode) {
    int angle = param.asInt();
    setServoAngle(SERVO_BASE, angle);
    Serial.print("Base: ");
    Serial.println(angle);
  }
}

BLYNK_WRITE(V1) {  // Shoulder angle (manual mode only)
  if (!autoMode) {
    int angle = param.asInt();
    setServoAngle(SERVO_SHOULDER, angle);
    Serial.print("Shoulder: ");
    Serial.println(angle);
  }
}

BLYNK_WRITE(V2) {  // Elbow angle (manual mode only)
  if (!autoMode) {
    int angle = param.asInt();
    setServoAngle(SERVO_ELBOW, angle);
    Serial.print("Elbow: ");
    Serial.println(angle);
  }
}

BLYNK_WRITE(V3) {  // Wrist angle (manual mode only)
  if (!autoMode) {
    int angle = param.asInt();
    setServoAngle(SERVO_WRIST, angle);
    Serial.print("Wrist: ");
    Serial.println(angle);
  }
}

BLYNK_WRITE(V4) {  // Gripper angle (manual mode only)
  if (!autoMode) {
    int angle = param.asInt();
    setServoAngle(SERVO_GRIPPER, angle);
    Serial.print("Gripper: ");
    Serial.println(angle);
  }
}

BLYNK_WRITE(V5) {  // Auto/Manual mode toggle
  autoMode = (param.asInt() == 1);
  Serial.println(autoMode ? "Auto mode ON" : "Manual mode ON");
}

BLYNK_WRITE(V6) {  // Reset all servos to default
  if (param.asInt() == 1) {
    setServoAngle(SERVO_BASE, 0);
    setServoAngle(SERVO_SHOULDER, 60);
    setServoAngle(SERVO_ELBOW, 70);
    setServoAngle(SERVO_WRIST, 60);
    setServoAngle(SERVO_GRIPPER, 90);
    Serial.println("Reset all servos to default");
    Blynk.virtualWrite(V0, 0);
    Blynk.virtualWrite(V1, 60);
    Blynk.virtualWrite(V2, 70);
    Blynk.virtualWrite(V3, 60);
    Blynk.virtualWrite(V4, 90);
  }
}

BLYNK_WRITE(V10) {  // Detection class from ESP32-CAM
  lastDetection = param.asString();
}

BLYNK_WRITE(V11) {  // Detection confidence from ESP32-CAM
  lastConfidence = param.asInt();
}

// Student-generated code goes here
void runStudentProgram() {
  {{GENERATED_CODE}}
}
