/*
 * Auto-generated by Block Robot IDE
 * Target: ESP32 (Arm Controller with AP Mode + WebSocket)
 */

#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <AsyncWebSocket.h>
#include <DNSServer.h>
#include <SPIFFS.h>
#include <Wire.h>
#include <Adafruit_PWMServoDriver.h>
#include <ArduinoJson.h>

// Access Point Configuration
const char* AP_SSID = "RobotArm-";  // Will append MAC address
String apSSID;
const char* AP_PASSWORD = "robot1234";
const IPAddress AP_IP(192, 168, 4, 1);
const IPAddress AP_GATEWAY(192, 168, 4, 1);
const IPAddress AP_SUBNET(255, 255, 255, 0);

// DNS Server for captive portal
DNSServer dnsServer;
const byte DNS_PORT = 53;

// Web Server and WebSocket
AsyncWebServer server(80);
AsyncWebSocket ws("/ws");

// PCA9685 servo driver
Adafruit_PWMServoDriver pwm = Adafruit_PWMServoDriver();

// I2C pins for ESP32
#define SDA_PIN 21
#define SCL_PIN 22

// Servo channel assignments
#define SERVO_BASE     0
#define SERVO_SHOULDER 1
#define SERVO_ELBOW    2
#define SERVO_WRIST    3
#define SERVO_GRIPPER  4

// PWM settings
#define SERVO_FREQ 50
#define SERVOMIN  150
#define SERVOMAX  600

// Default servo positions
const int DEFAULT_POSITIONS[5] = {0, 60, 70, 60, 90};

// Operating mode
bool autoMode = false;

// Current servo positions
int currentPos[5] = {0, 60, 70, 60, 90};

// Pose definitions (generated from IDE)
{{POSE_DEFINITIONS}}

// Helper function: Convert angle to PWM pulse
int angleToPulse(int angle) {
  angle = constrain(angle, 0, 180);
  return map(angle, 0, 180, SERVOMIN, SERVOMAX);
}

// Helper function: Set servo position
void setServoAngle(uint8_t channel, int angle) {
  int pulse = angleToPulse(angle);
  pwm.setPWM(channel, 0, pulse);

  if (channel < 5) {
    currentPos[channel] = angle;
  }
}

// Send current state to all WebSocket clients
void broadcastState() {
  StaticJsonDocument<200> doc;
  doc["type"] = "state";
  JsonArray servos = doc.createNestedArray("servos");
  for (int i = 0; i < 5; i++) {
    servos.add(currentPos[i]);
  }
  doc["auto"] = autoMode;

  String json;
  serializeJson(doc, json);
  ws.textAll(json);
}

// Handle WebSocket message
void handleWebSocketMessage(void *arg, uint8_t *data, size_t len) {
  AwsFrameInfo *info = (AwsFrameInfo*)arg;
  if (info->final && info->index == 0 && info->len == len && info->opcode == WS_TEXT) {
    data[len] = 0;
    String message = (char*)data;

    StaticJsonDocument<200> doc;
    DeserializationError error = deserializeJson(doc, message);

    if (error) {
      Serial.print("JSON parse error: ");
      Serial.println(error.c_str());
      return;
    }

    const char* type = doc["type"];

    if (strcmp(type, "servo") == 0) {
      int channel = doc["channel"];
      int angle = doc["angle"];

      if (channel >= 0 && channel <= 4 && angle >= 0 && angle <= 180) {
        setServoAngle(channel, angle);
        Serial.printf("Servo %d -> %d°\n", channel, angle);
        broadcastState();
      }
    }
    else if (strcmp(type, "mode") == 0) {
      autoMode = doc["auto"];
      Serial.println(autoMode ? "Auto mode ON" : "Manual mode ON");
      broadcastState();
    }
    else if (strcmp(type, "reset") == 0) {
      for (int i = 0; i < 5; i++) {
        setServoAngle(i, DEFAULT_POSITIONS[i]);
      }
      Serial.println("Reset to defaults");
      broadcastState();
    }
  }
}

// WebSocket event handler
void onWebSocketEvent(AsyncWebSocket *server, AsyncWebSocketClient *client, AwsEventType type,
                       void *arg, uint8_t *data, size_t len) {
  switch (type) {
    case WS_EVT_CONNECT:
      Serial.printf("WebSocket client #%u connected from %s\n", client->id(), client->remoteIP().toString().c_str());
      // Send current state to new client
      broadcastState();
      break;

    case WS_EVT_DISCONNECT:
      Serial.printf("WebSocket client #%u disconnected\n", client->id());
      break;

    case WS_EVT_DATA:
      handleWebSocketMessage(arg, data, len);
      break;

    case WS_EVT_PONG:
    case WS_EVT_ERROR:
      break;
  }
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println("\n\nStarting Robot Arm Controller (AP Mode)...");

  // Generate unique SSID from MAC address
  uint8_t mac[6];
  WiFi.macAddress(mac);
  apSSID = String(AP_SSID) + String(mac[4], HEX) + String(mac[5], HEX);
  apSSID.toUpperCase();

  Serial.print("SSID: ");
  Serial.println(apSSID);
  Serial.print("Password: ");
  Serial.println(AP_PASSWORD);

  // Initialize I2C and PCA9685
  Wire.begin(SDA_PIN, SCL_PIN);
  pwm.begin();
  pwm.setPWMFreq(SERVO_FREQ);
  delay(10);

  // Set servos to default positions
  for (int i = 0; i < 5; i++) {
    setServoAngle(i, DEFAULT_POSITIONS[i]);
  }
  Serial.println("PCA9685 initialized");

  // Initialize SPIFFS
  if (!SPIFFS.begin(true)) {
    Serial.println("SPIFFS Mount Failed");
    return;
  }
  Serial.println("SPIFFS mounted");

  // Configure Access Point
  WiFi.mode(WIFI_AP);
  WiFi.softAPConfig(AP_IP, AP_GATEWAY, AP_SUBNET);
  WiFi.softAP(apSSID.c_str(), AP_PASSWORD);

  Serial.print("AP IP address: ");
  Serial.println(WiFi.softAPIP());

  // Start DNS server for captive portal
  dnsServer.start(DNS_PORT, "*", AP_IP);
  Serial.println("DNS server started");

  // Setup WebSocket
  ws.onEvent(onWebSocketEvent);
  server.addHandler(&ws);

  // Serve PWA files from SPIFFS
  server.serveStatic("/", SPIFFS, "/").setDefaultFile("index.html");

  // Captive portal redirect
  server.onNotFound([](AsyncWebServerRequest *request){
    request->redirect("/");
  });

  // Start web server
  server.begin();
  Serial.println("Web server started");
  Serial.println("Ready! Connect to WiFi and open browser.");
}

void loop() {
  dnsServer.processNextRequest();
  ws.cleanupClients();

  if (autoMode) {
    runStudentProgram();
    delay(100);
  }

  delay(10);
}

// Helper functions for generated code
void moveArmToPose(const int pose[5]) {
  for (int i = 0; i < 5; i++) {
    setServoAngle(i, pose[i]);
  }
  delay(500);
}

void openClaw() {
  setServoAngle(SERVO_GRIPPER, 30);
  delay(300);
}

void closeClaw() {
  setServoAngle(SERVO_GRIPPER, 90);
  delay(300);
}

bool cameraSees(const String& className, int minConfidence) {
  // Placeholder for future ESP32-CAM integration
  return false;
}

// Student-generated code
void runStudentProgram() {
  {{GENERATED_CODE}}
}
